// === comps ===
//    === Admin ===
export const PROFILES_GET = 'PROFILES_GET';

export const AD_FILTER_RESULT = 'AD_FILTER_RESULT';
export const AD_FILTER_RESULT_ERROR = 'AD_FILTER_RESULT_ERROR';
export const AD_FILTER_UPDATE = 'AD_FILTER_UPDATE';
export const AD_FILTER_ERROR = 'AD_FILTER_ERROR';
export const AD_TRACK_UPDATE_GENUS = 'AD_TRACK_UPDATE_GENUS';
export const AD_TRACK_UPDATE_FAMILY = 'AD_TRACK_UPDATE_FAMILY';
export const AD_TRACK_UPDATE_ERROR = 'AD_TRACK_UPDATE_ERROR';
export const AD_SPECIES_COUNT = 'AD_SPECIES_COUNT';
export const AD_SPECIES_GOOD = 'AD_SPECIES_GOOD';
export const AD_SPECIES_ERROR = 'AD_SPECIES_ERROR';

export const AD_SET_ART_GENUS = 'AD_SET_ART_GENUS';
export const AD_SET_ARTIST_NOW = 'AD_SET_ARTIST_NOW';
export const AD_ARTIST_RESULT = 'AD_ARTIST_RESULT';
export const AD_ARTIST_RESULT_ERROR = 'AD_ARTIST_RESULT_ERROR';
export const AD_ARTIST_COUNT = 'AD_ARTIST_COUNT';
export const AD_ARTIST_COUNT_ERROR = 'AD_ARTIST_COUNT_ERROR';
export const AD_ARTIST_UPDATE = 'AD_ARTIST_UPDATE';
export const AD_ARTIST_UPDATE_ERROR = 'AD_ARTIST_UPDATE_ERROR';

export const AD_SET_PLAYLIST_NOW = 'AD_SET_PLAYLIST_NOW';
export const AD_PLAYLIST_RESULT = 'AD_PLAYLIST_RESULT';
export const AD_PLAYLIST_RESULT_ERROR = 'AD_PLAYLIST_RESULT_ERROR';
export const AD_PLAYLIST_COUNT = 'AD_PLAYLIST_COUNT';
export const AD_PLAYLIST_COUNT_ERROR = 'AD_PLAYLIST_COUNT_ERROR';
export const AD_PLAYLIST_CREATE = 'AD_PLAYLIST_CREATE';
export const AD_PLAYLIST_CREATE_ERROR = 'AD_PLAYLIST_CREATE_ERROR';
export const AD_PLAYLIST_UPDATE = 'AD_PLAYLIST_UPDATE';
export const AD_PLAYLIST_UPDATE_ERROR = 'AD_PLAYLIST_UPDATE_ERROR';
export const AD_PLAYLIST_DELETE = 'AD_PLAYLIST_DELETE';
export const AD_PLAYLIST_ERROR = 'AD_PLAYLIST_ERROR';

export const AD_PLAYALL_GET_ADMIN = 'AD_PLAYALL_GET_ADMIN';
export const AD_PLAYALL_GET_USER = 'AD_PLAYALL_GET_USER';
export const AD_PLAYALL_ERROR = 'AD_PLAYALL_ERROR';
//    === Ecomm ===

//    === Library ===
export const LIBRARY_GET = 'LIBRARY_GET';
export const LIBRARY_ERROR = 'LIBRARY_ERROR';
export const LIB_RESULT_INIT = 'LIB_RESULT_INIT';
export const LIB_RESULT_SET = 'LIB_RESULT_SET';
export const LIB_RESULT_CLEAR = 'LIB_RESULT_CLEAR';
export const LIB_RESULT_ERROR = 'LIB_RESULT_ERROR';
export const LIB_TYPE_SET = 'LIB_TYPE_SET';
export const SET_OFFSET = 'SET_OFFSET';

export const ARTIST_RESULT = 'ARTIST_RESULT';
export const ARTIST_GET = 'ARTIST_GET';
export const ARTIST_ERROR = 'ARTIST_ERROR';
export const ARTISTS_GET = 'ARTISTS_GET';
export const ARTISTS_ERROR = 'ARTISTS_ERROR';

export const TRK_SELECT = 'TRK_SELECT';
export const TRK_UPDATE = 'TRK_UPDATE';
export const TRK_CLEAR = 'TRK_CLEAR';
export const TRK_ERROR = 'TRK_ERROR';

export const PLAYLIST_RESULT = 'PLAYLIST_RESULT';
export const PLAYLIST_GET_ADMIN = 'PLAYLIST_GET_ADMIN';
export const PLAYLIST_GET_USER = 'PLAYLIST_GET_USER';
export const PLAYLIST_GET_FAV = 'PLAYLIST_GET_FAV';
export const PLAYLIST_SELECT = 'PLAYLIST_SELECT';
export const PLAYLIST_CREATE = 'PLAYLIST_CREATE';
export const PLAYLIST_UPDATE = 'PLAYLIST_UPDATE';
export const PLAYLIST_DELETE = 'PLAYLIST_DELETE';
export const PLAYLIST_ERROR_ADMIN = 'PLAYLIST_ERROR_ADMIN';
export const PLAYLIST_ERROR_USER = 'PLAYLIST_ERROR_USER';
export const PLAYLIST_ERROR_FAV = 'PLAYLIST_ERROR_FAV';
export const PLAYLIST_ERROR = 'PLAYLIST_ERROR';

export const FILTER_RESULT = 'FILTER_RESULT';
export const FILTER_UPDATE = 'FILTER_UPDATE';
export const FILTER_CLEAR = 'FILTER_CLEAR';
export const FILTER_ERROR = 'FILTER_ERROR';
export const SET_GENUS_NOW = 'SET_GENUS_NOW';
export const SET_GENUS_ERROR = 'SET_GENUS_ERROR';

export const SEARCH_RESULT = 'SEARCH_RESULT';
export const SEARCH_UPDATE = 'SEARCH_UPDATE';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';
export const SEARCH_ERROR = 'SEARCH_ERROR';

export const TRAITS_GET = 'TRAITS_GET';
export const TRAITS_CLEAR = 'TRAITS_CLEAR';
export const TRAITS_ERROR = 'TRAITS_ERROR';
export const SPECIES_GET = 'SPECIES_GET';

export const ITEMS_GET = 'ITEMS_GET';
export const ITEMS_ERROR = 'ITEMS_ERROR';
//    === Main ===

//    === Warn ===
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//    === User ===
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_LOADED = 'USER_LOADED';
export const USER_LOAD_ERROR = 'USER_LOAD_ERROR';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const PROFILE_GET = 'PROFILE_GET';
export const PROFILE_CREATE = 'PROFILE_CREATE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const PROFILE_CLEAR = 'PROFILE_CLEAR';
export const PROFILE_UPDATE = 'PROFILE_UPDATE';

export const FAVORITE_GET = 'FAVORITE_GET';
export const FAVORITE_UPDATE = 'FAVORITE_UPDATE';
export const FAVORITE_ERROR = 'FAVORITE_ERROR';

//    === User ===
export const UP_IMAGE = 'UP_IMAGE';
export const UP_IMAGE_ERROR = 'UP_IMAGE_ERROR';
export const UP_AUDIO = 'UP_AUDIO';
export const UP_AUDIO_ERROR = 'UP_AUDIO_ERROR';
